### ISSUE TITLE
User-friendly presentation of exceptions in seash

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/seash#67]
A Sensibility Testbed user reports having seen this traceback:

```
ajksdf@ !> contact 10.2.2.193:1224
Traceback (most recent call last):
  File "seash.py", line 267, in command_loop
  File "/Users/justincappos/Downloads/sensor/seattle_demokit/seash_dictionary.py", line 2109, in command_dispatch
  File "/Users/justincappos/Downloads/sensor/seattle_demokit/command_callbacks.py", line 977, in contact
  File "/Users/justincappos/Downloads/sensor/seattle_demokit/nmclient", line 238, in nmclient_createhandle
NMClientException: Timed-out connecting to the remote host!
```

The root cause left aside, we shouldn't present a raw traceback to the unsuspecting user. The last line should probably suffice so that the devels can locate where the problem arose (but see #1289 on unique exception messages!).

**Comment by aaaaalbert** [comment]
Superseded by #84.
